# Generated by Django 2.1.1 on 2018-09-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180925_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
