# Generated by Django 2.1.1 on 2018-09-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default='', max_length=200),
        ),
    ]
